### ISSUE TITLE
gulp-browserify

### ISSUE THREAD

**Issue by bramdevries** [unfold/browserify-hogan#9]
I use gulp-browserify in my build process and I seem to be getting errors when using this. 

I require my template like so:

```
template: require('../Templates/invoiceDetail.ms'),
```

but when running gulp I get the following error:

```
/Users/bramdevries/Documents/School/2013-2014 3 Devine/Stage/Madewithlove/kaash/public/app/js/Templates/invoiceDetail.ms:1
<p>Hello</p>
^
ParseError: Unexpected token <
    at wrapWithPluginError (/Users/bramdevries/Documents/School/2013-2014 3 Devine/Stage/Madewithlove/kaash/node_modules/gulp-browserify/index.js:44:10)
    at Stream.<anonymous> (/Users/bramdevries/Documents/School/2013-2014 3 Devine/Stage/Madewithlove/kaash/node_modules/gulp-browserify/index.js:103:28)
    at Stream.<anonymous> (/Users/bramdevries/Documents/School/2013-2014 3 Devine/Stage/Madewithlove/kaash/node_modules/gulp-browserify/node_modules/browserify/index.js:299:22)
    at Stream.EventEmitter.emit (events.js:117:20)
    at Stream.onerror (/Users/bramdevries/Documents/School/2013-2014 3 Devine/Stage/Madewithlove/kaash/node_modules/gulp-browserify/node_modules/browserify/node_modules/stream-combiner/index.js:29:18)
    at Stream.EventEmitter.emit (events.js:117:20)
    at Stream.<anonymous> (/Users/bramdevries/Documents/School/2013-2014 3 Devine/Stage/Madewithlove/kaash/node_modules/gulp-browserify/node_modules/browserify/index.js:527:30)
    at Stream.stream.write (/Users/bramdevries/Documents/School/2013-2014 3 Devine/Stage/Madewithlove/kaash/node_modules/gulp-browserify/node_modules/browserify/node_modules/through/index.js:26:11)
    at Stream.ondata (stream.js:51:26)
    at Stream.EventEmitter.emit (events.js:95:17)
```

**Comment by bramdevries** [comment]
I forgot to add it to my transforms array in gulp, apologies.
